apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app1
  namespace: default
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: nginx-app1
  template:
    metadata:
      labels:
        app: nginx-app1
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
